export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIEGENRE1 = 'FETCH_MOVIEGENRE1';
export const FETCH_MOVIEGENRE2 = 'FETCH_MOVIEGENRE2';
export const FETCH_MOVIEGENRE3 = 'FETCH_MOVIEGENRE3';
